### PR TITLE
Free memory

### PR DESCRIPTION
**Pull request by sbly**
https://themuse.atlassian.net/browse/SVC-375 SVC-375

### CODE REVIEW

**Comment by ian-axelrod** [comment]
How's the memory usage look now? How'd you test that?

**Comment by sbly** [comment]
I attached https://pypi.python.org/pypi/memory_profiler to the pilbox process inside the docker container. I can see memory being allocated when the image is resized, and freed on the `del` call. It should hover around 30-40 mb.

**Comment by ian-axelrod** [comment]
Gotcha. Welp, let's see if this does the trick!

**Review by ian-axelrod — APPROVED** [review]

**Comment by ian-axelrod** [comment]
We'll need to update docker-pilbox too, right?

**Comment by sbly** [comment]
oh right forgot about that - will do

**Pull request merged**
